spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}