CREATE TABLE IF NOT EXISTS loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    borrowed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    returned_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_loans_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_loans_book FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE INDEX IF NOT EXISTS idx_loans_member_id ON loans (member_id);
CREATE INDEX IF NOT EXISTS idx_loans_book_id ON loans (book_id);
CREATE INDEX IF NOT EXISTS idx_loans_returned_at ON loans (returned_at);
CREATE INDEX IF NOT EXISTS idx_loans_borrowed_at ON loans (borrowed_at);

CREATE UNIQUE INDEX IF NOT EXISTS uk_loans_active_member_book
    ON loans (member_id, book_id)
    WHERE returned_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_loans_active_book
    ON loans (book_id)
    WHERE returned_at IS NULL;

INSERT INTO loans (member_id, book_id, borrowed_at, returned_at)
SELECT mb.member_id, mb.book_id, CURRENT_TIMESTAMP, NULL
FROM member_books mb
WHERE NOT EXISTS (
    SELECT 1
    FROM loans l
    WHERE l.member_id = mb.member_id
      AND l.book_id = mb.book_id
      AND l.returned_at IS NULL
);
