-- Remove leftover integration/E2E member placeholders that clutter the Members admin list.
-- These emails are generated by tests (UUID / timestamp suffixes), not demo accounts.

WITH doomed AS (
    SELECT id
    FROM members
    WHERE email LIKE 'borrower-%@library.com'
       OR email LIKE 'register-%@library.com'
       OR email LIKE 'e2e.%@library.com'
       OR email LIKE 'e2e-%@library.com'
       OR email LIKE 'attach-%@library.com'
       OR email LIKE 'swagger-verify-%@library.com'
)
DELETE FROM loans
WHERE member_id IN (SELECT id FROM doomed);

WITH doomed AS (
    SELECT id
    FROM members
    WHERE email LIKE 'borrower-%@library.com'
       OR email LIKE 'register-%@library.com'
       OR email LIKE 'e2e.%@library.com'
       OR email LIKE 'e2e-%@library.com'
       OR email LIKE 'attach-%@library.com'
       OR email LIKE 'swagger-verify-%@library.com'
)
DELETE FROM member_books
WHERE member_id IN (SELECT id FROM doomed);

DELETE FROM members
WHERE email LIKE 'borrower-%@library.com'
   OR email LIKE 'register-%@library.com'
   OR email LIKE 'e2e.%@library.com'
   OR email LIKE 'e2e-%@library.com'
   OR email LIKE 'attach-%@library.com'
   OR email LIKE 'swagger-verify-%@library.com';

-- Prefer a proper display name when name was stored as a duplicate of the email.
UPDATE members
SET name = 'Attach Admin'
WHERE email = 'attach-admin@library.com'
  AND name = email;

UPDATE members
SET name = 'Attach User'
WHERE email = 'attach-user@library.com'
  AND name = email;
